package de.linnk.semantic;

import thewebsemantic.Namespace;
import thewebsemantic.vocabulary.Sioc;

import com.hp.hpl.jena.ontology.DatatypeProperty;
import com.hp.hpl.jena.ontology.Individual;
import com.hp.hpl.jena.ontology.ObjectProperty;
import com.hp.hpl.jena.ontology.OntClass;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;
/**
 * Vocabulary definitions from file:/Applications/Protege_3.3.1/schemagen-temp.owl 
 * @author Auto-generated by schemagen on 01 Mrz 2009 00:18 
 */
public class BasicOntology {
	 @Namespace("http://www.linnk.de/basic.rdf#")
	public interface Linnk extends Sioc {
		public interface Document extends Linnk {};
		
		//Linnk has_creator(Object t);
	  //  Collection<Thing> has_creator();
	    
	   // Linnk content(Object t);
	   // Collection<Thing> content();
	
	}

	/** <p>The ontology model that holds the vocabulary terms</p> */
    public static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.linnk.de/basic.rdf#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Describes how a document/item is composed of Items</p> */
    public static final ObjectProperty composedOf = m_model.createObjectProperty( "http://www.linnk.de/basic.rdf#composedOf" );
    
    /** <p>Describes how an Item is part of a Document</p> */
    public static final ObjectProperty partOf = m_model.createObjectProperty( "http://www.linnk.de/basic.rdf#partOf" );
    
    /** <p>Describes how a TexItem has a text</p> */
    public static final DatatypeProperty hasText = m_model.createDatatypeProperty( "http://www.linnk.de/basic.rdf#hasText" );
    
    /** <p>Text (as TextItem)</p> */
    public static final OntClass Text = m_model.createClass( "http://www.linnk.de/basic.rdf#Text" );
    
    /** <p>Linnk document</p> */
    public static final OntClass Document = m_model.createClass( "http://www.linnk.de/basic.rdf#Document" );
    
    /** <p>Element of Linnk data model</p> */
    public static final OntClass LinnkElement = m_model.createClass( "http://www.linnk.de/basic.rdf#LinnkElement" );
    
    /** <p>Representing an Item in Linnk that can be part of a document</p> */
    public static final OntClass Item = m_model.createClass( "http://www.linnk.de/basic.rdf#Item" );
    
    public static final Individual Document1 = m_model.createIndividual( "http://www.linnk.de/basic.rdf#Document1", Document );

    
}
